\connect db_microservicios_usuarios

CREATE SCHEMA clientes;
ALTER SCHEMA clientes OWNER TO postgres;

CREATE SCHEMA descuentos;
ALTER SCHEMA descuentos OWNER TO postgres;

CREATE SCHEMA facturas;
ALTER SCHEMA facturas OWNER TO postgres;

CREATE TABLE clientes.catalog_tipos_usuario (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descripcion character varying(250),
    valor character varying(100)
);

ALTER TABLE clientes.catalog_tipos_usuario OWNER TO postgres;

ALTER TABLE clientes.catalog_tipos_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clientes.catalog_tipos_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 16426)
-- Name: usuarios; Type: TABLE; Schema: clientes; Owner: postgres
--

CREATE TABLE clientes.usuarios (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    apellido_materno character varying(100),
    apellido_paterno character varying(100),
    email character varying(50),
    nombre character varying(50),
    cat_tipo_usuario_id bigint
);


ALTER TABLE clientes.usuarios OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 16424)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: clientes; Owner: postgres
--

ALTER TABLE clientes.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clientes.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 16443)
-- Name: catalog_tipo_acumulacion_descuento; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.catalog_tipo_acumulacion_descuento (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descripcion character varying(250),
    valor character varying(100)
);


ALTER TABLE descuentos.catalog_tipo_acumulacion_descuento OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 16441)
-- Name: catalog_tipo_acumulacion_descuento_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.catalog_tipo_acumulacion_descuento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.catalog_tipo_acumulacion_descuento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16535)
-- Name: catalog_tipo_condicion_descuento_cantidad; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.catalog_tipo_condicion_descuento_cantidad (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descripcion character varying(250),
    valor character varying(100)
);


ALTER TABLE descuentos.catalog_tipo_condicion_descuento_cantidad OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16533)
-- Name: catalog_tipo_condicion_descuento_cantidad_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.catalog_tipo_condicion_descuento_cantidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.catalog_tipo_condicion_descuento_cantidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16450)
-- Name: catalog_tipo_condicion_descuento_usuario; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.catalog_tipo_condicion_descuento_usuario (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descripcion character varying(250),
    valor character varying(100)
);


ALTER TABLE descuentos.catalog_tipo_condicion_descuento_usuario OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16448)
-- Name: catalog_tipo_condicion_descuento_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.catalog_tipo_condicion_descuento_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.catalog_tipo_condicion_descuento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16457)
-- Name: catalog_tipo_descuento; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.catalog_tipo_descuento (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descripcion character varying(250),
    valor character varying(100)
);


ALTER TABLE descuentos.catalog_tipo_descuento OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16455)
-- Name: catalog_tipo_descuento_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.catalog_tipo_descuento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.catalog_tipo_descuento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16464)
-- Name: catalog_tipo_producto; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.catalog_tipo_producto (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descripcion character varying(250),
    valor character varying(100)
);


ALTER TABLE descuentos.catalog_tipo_producto OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16462)
-- Name: catalog_tipo_producto_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.catalog_tipo_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.catalog_tipo_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16471)
-- Name: descuento_por_tipo_producto; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.descuento_por_tipo_producto (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descuento_id bigint,
    cat_tipo_producto_id bigint
);


ALTER TABLE descuentos.descuento_por_tipo_producto OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16469)
-- Name: descuento_por_tipo_producto_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.descuento_por_tipo_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.descuento_por_tipo_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16478)
-- Name: descuentos; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.descuentos (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    valor_condicion character varying(255),
    valor_descuento character varying(255),
    cat_tipo_acumulacion_descuento_id bigint,
    cat_tipo_descuento_id bigint,
    cat_tipo_condicion_descuento_usuario_id bigint,
    cat_tipo_condicion_descuento_cantidad_id bigint
);


ALTER TABLE descuentos.descuentos OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16476)
-- Name: descuentos_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.descuentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.descuentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16488)
-- Name: productos; Type: TABLE; Schema: descuentos; Owner: postgres
--

CREATE TABLE descuentos.productos (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descripcion character varying(250),
    valor character varying(100),
    precio real,
    cat_tipo_producto_id bigint
);


ALTER TABLE descuentos.productos OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16486)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: descuentos; Owner: postgres
--

ALTER TABLE descuentos.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME descuentos.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16594)
-- Name: descuentos_por_factura; Type: TABLE; Schema: facturas; Owner: postgres
--

CREATE TABLE facturas.descuentos_por_factura (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    descuento_id bigint,
    factura_id bigint
);


ALTER TABLE facturas.descuentos_por_factura OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16592)
-- Name: descuentos_por_factura_id_seq; Type: SEQUENCE; Schema: facturas; Owner: postgres
--

ALTER TABLE facturas.descuentos_por_factura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturas.descuentos_por_factura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16601)
-- Name: facturas; Type: TABLE; Schema: facturas; Owner: postgres
--

CREATE TABLE facturas.facturas (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    id_usuario bigint,
    total_descuento real,
    total_sin_descuento real
);


ALTER TABLE facturas.facturas OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16599)
-- Name: facturas_id_seq; Type: SEQUENCE; Schema: facturas; Owner: postgres
--

ALTER TABLE facturas.facturas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturas.facturas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16608)
-- Name: productos_carrito; Type: TABLE; Schema: facturas; Owner: postgres
--

CREATE TABLE facturas.productos_carrito (
    id bigint NOT NULL,
    estatus boolean,
    fec_crea timestamp without time zone,
    cantidad integer,
    factura_id bigint,
    producto_id bigint
);


ALTER TABLE facturas.productos_carrito OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16606)
-- Name: productos_carrito_id_seq; Type: SEQUENCE; Schema: facturas; Owner: postgres
--

ALTER TABLE facturas.productos_carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturas.productos_carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);